version: '2'

services:
    mariadb:
        image: 'docker.io/bitnami/mariadb:10.1-debian-10'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=my_user
            - MARIADB_DATABASE=my_database
            - MARIADB_PASSWORD=my_password

    myapp:
        tty: true
        image: docker.io/bitnami/laravel:7-debian-10
        depends_on:
            - mariadb
        ports:
            - 80:3000
        volumes:
            - ./:/app